# Generated by Django 3.0.8 on 2020-07-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addsongs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.CharField(max_length=100),
        ),
    ]
